version: "3.9"

services:
  faster-whisper:
    image: lscr.io/linuxserver/faster-whisper:latest
    container_name: faster-whisper
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/London"
      WHISPER_BEAM: "1"
      WHISPER_LANG: "auto"
      WHISPER_MODEL: "medium"
    volumes:
      - /DATA/AppData/faster-whisper/config:/config
    ports:
      - "10300:10300"
    networks:
      - audio-net
    restart: unless-stopped

  audio-hub:
    image: ghcr.io/drummas/audio-hub:release
    container_name: audio-hub
    depends_on:
      - faster-whisper
    environment:
      FASTER_WHISPER_URL: "http://faster-whisper:10300/inference"
      XTTS_LANGUAGE: "en"
      XTTS_VOICE: "default"
      WHISPER_BEAM: "1"
      WHISPER_LANG: "auto"
      WHISPER_MODEL: "medium"
      DEFAULT_TRANSLATION_LANGUAGE: "pt"
      COQUI_TOS_AGREED: "1"
    volumes:
      - /DATA/AppData/audio-hub/files:/app/files
      - /DATA/AppData/audio-hub/batches:/app/batches
      - /DATA/AppData/audio-hub/waveforms:/app/waveforms
      - /DATA/AppData/audio-hub/speakers:/app/speakers
      - /DATA/AppData/audio-hub/config:/app/config
      - /DATA/AppData/audio-hub/tts-cache:/root/.local/share/tts
    ports:
      - "8000:8000"
    networks:
      - audio-net
    restart: unless-stopped

networks:
  audio-net: